### ISSUE TITLE
[FeatureRequest]  incorporating DiskFileItemFactory in Apache Commons FileUpload

### ISSUE THREAD

**Issue by JerryChin** [Revanka/paint-upload#7]
Hey, It's me again!

Before coming across your project, We had adopted Apache Commons FileUpload for a very long time, it's very simple to use, one of its classes is `FileItem`, which contains all information you need to know about a part, much like `PartStream` in your library,  it's been backed by `DiskFileItemFactory`.

The goodness of `DiskFileItemFactory` is that it provides an IO efficient streaming implementation, as long as the part size is below memory threshold, it will get buffered, and automatically flush to disk when it's getting too bigger.

**I think that by incorporating ``DiskFileItemFactory` into this library, it would be much easier for developers to handle uploaded files.**

Currently, the meta info and its content of a part are stored in different place, eg.  `PartStream`  and user supplied `PathOutput`, it's not very easily to use.  You should check out how `FileItem` is defined.

 **Here's another suggestion (not sure if I should create a new issue)**  

`UploadContext#getPartStreams` returns a list, it would be better to return a map, so it will be faster to find the part we're concerned.

The above suggestions have been implemented in our fork, here's our implementation:

AbstractUploadParser
```
    @Override
    public void beginPart(final FileItemHeaders headers) throws IOException {
        final String disposition = headers.getHeader(Headers.CONTENT_DISPOSITION);
        if (disposition != null && disposition.startsWith("form-data")) {
            String fieldName = Headers.extractQuotedValueFromHeader(disposition, "name");
            String fileName = Headers.extractQuotedValueFromHeader(disposition, "filename");

            FileItem item = fileItemFactory.createItem(fieldName,
                    headers.getHeader(Headers.CONTENT_TYPE), fileName == null, fileName);
            item.setHeaders(headers);
            outputStream = item.getOutputStream();
            context.reset(item);
        }
    }

    @Override
    public void data(final ByteBuffer buffer) throws IOException {
        checkPartSize(buffer.remaining());
        outputStream.write(buffer.array(), buffer.arrayOffset() + buffer.position(), buffer.remaining());
        buffer.position(buffer.limit());
    }

    @Override
    public void endPart() throws IOException {
        outputStream.close();
        if (partEndCallback != null) {
            partEndCallback.onPartEnd(context);
        }
    }
```

UploadContextImpl

```
   /**
     * The map of the already processed items, field name is key.
     */
    private final Map<String, FileItem> items = new HashMap<>();

    @Override
    public Map<String, FileItem> getItemMap() {
        return Collections.unmodifiableMap(items);
    }
```

What do you think?

**Comment by Elopteryx** [comment]
Hi Jerry,

I know about Apache Commons FileUpload, I created this library as an even lower-level version of it, so that everything can be customized by the applications, if they need it. PartStream is based on FileItem. Adding a class like DiskFileItemFactory would defeat that point, with that I would just recreate the Apache library.
If you want a simple Outputstream that flushes to the disk after a threshold then you can use something like https://guava.dev/releases/21.0/api/docs/com/google/common/io/FileBackedOutputStream.html
which can be wrapped with https://github.com/Elopteryx/upload-parser/blob/master/upload-parser-core/src/main/java/com/github/elopteryx/upload/PartOutput.java#L84

For the Map suggestion, I'm not sure, the List is necessary. As the bytes arrive it gets filled in the order the parts arrive, with a HashMap you would lose that order. With a LinkedHashMap the order could be preserved, but that would still mean storing the items twice.
If you need a quick lookup, you can solve it with the current code, in the application the parser is called:

```
Map<String, PartStream> items = new HashMap<>();
UploadParser.newParser()
                    .onPartBegin((context, buffer) -> {
                        PartStream part = context.getCurrentPart();
                        items.put(part.getName(), part);
                        ...
                     }
```
With that you would have a Map for the current request and can use it anywhere.

**Comment by JerryChin** [comment]
That makes a lot of sense, thank you for your response.
